### GET request to example server
GET localhost:8006/api/coupon/1

### Post request
POST localhost:8006/api/coupon/register/1
Content-Type: application/json

{
  "clientId": 1,
  "expirationDate": "2024-06-05T15:55:08",
  "couponPolicyId": 1,
  "couponTypeId": 1,
  "status": "AVAILABLE"

}

### put Test
PUT localhost:8006/api/coupon/update
Content-Type: application/json

{
  "couponId": 2
}



###POST
POST localhost:8006/api/client/welcome/1
