###GET
GET localhost:8006/admin/coupon/policy/1
###GET
GET localhost:8006/admin/coupon/policy
###POST
POST localhost:8006/admin/coupon/policy/register
Content-Type: application/json

{
  "productId": null,
  "productCategoryId": null,
  "couponPolicyDescription": "description",
  "discountType": "AMOUNTDISCOUNT",
  "discountValue": 10000,
  "minPurchaseAmount": 0,
  "maxDiscountAmount": 10000

}